<style type="text/css">
	.opc-index-index #dd_method_emi{
		font-size: 14px;
	}
</style>
<!-- <h4 class="tab-title">Pay by Credit Card/Debit Card/Net Banking </h4> -->
<fieldset class="form-list">
    <?php /* $_code=$this->getMethodCode() */?>
    <?php /*
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to Payment Gateway to complete your order.') ?>
        </li>
        <li class="payment-form-description">
          <span>By clicking on Place Order, you agree to <a href="/termsandconditions" alt="Terms and condition"> Terms of Use </a> and <a href="/privacypolicy" alt="Privacy Policy">Privacy Policy </a> of Tresmode.com.
        </li>
    </ul>
</fieldset> */?>
<?php /*
<div class="buttons-set" id="payment-buttons-container">
    <a class="button cashondeliverypaymentbutton" onclick="payment.save()">
    <span><span><?php // echo $this->__('Pay Now') ?></span></span>
    </a>
</div>*/?>